/*
==============================================================================

	DermokerE398 - MP5 Viewmodel

==============================================================================
*/

$modelname "v_9mmAR.mdl"
$cd "./SMD"
$cdtexture ./maps_8bit
$scale 1 

// whole body
$body studio "mp5sd"

// origin: y x z
$origin 0 15 9

$sequence idle1 "idle1" fps 35 
$sequence grenade "grenadeshoot" fps 30 
$sequence reload "reload" fps 20
$sequence shoot "shoot1" fps 15
$sequence shoot "shoot2" fps 15
$sequence shoot "shoot3" fps 15



